### ISSUE TITLE
German translations are not visible for customers

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix-venueless#1]
I activated German and German (informal) on a recent pretix installation. Part of the venueless-plugin-options are translated, but the customer website, where they click on "Join live event" are not completely translated. I tried to reinstall the plugin just today with --no-cache options in a fresh docker-container. It seems like translation are available in a .po file but now shown. 

<img width="951" alt="Backend" src="https://user-images.githubusercontent.com/1153741/87152994-ffd1d700-c2b6-11ea-8041-c9720af2ecd0.png">
<img width="1170" alt="Customer" src="https://user-images.githubusercontent.com/1153741/87153000-02343100-c2b7-11ea-85fb-121fe19471a3.png">

**Comment by saschafoerster** [comment]
<img width="627" alt="Option later" src="https://user-images.githubusercontent.com/1153741/87153620-0c0a6400-c2b8-11ea-8828-59c935b5a4b3.png">

**Comment by raphaelm** [comment]
Can you show the full dockerfile? Might be the order of commands

**Comment by saschafoerster** [comment]
```
FROM pretix/standalone:stable
USER root
RUN pip3 install pretix-pages pretix-fontpack-free pretix-sepadebit pretix-cartshare pretix-passbook
RUN pip install -Ue "git+https://github.com/pretix/pretix-venueless.git@master#egg=pretix-venueless"
RUN cd /pretix/src && sudo -u pretixuser make production
USER pretixuser
```

**Comment by saschafoerster** [comment]
Together with @raphaelm we tried this dockerfile, and then it worked: 

```
FROM pretix/standalone:stable
USER root
RUN pip3 install pretix-pages pretix-fontpack-free pretix-sepadebit pretix-cartshare pretix-passbook
RUN DJANGO_SETTINGS_MODULE=pretix.settings pip install -U "git+https://github.com/pretix/pretix-venueless.git@master#egg=pretix-venueless"
RUN cd /pretix/src && sudo -u pretixuser make production
USER pretixuser
```
